# Final Project 

In [48]:
import pandas as pd
import os

# Set the working directory
os.chdir("/Users/teri/Documents/GitHub/Energy10k")

company_metadata_2024 = pd.read_csv("metadata2024.csv")
labeled_270 = pd.read_csv("sample_270_coded.csv")
unlabeled = pd.read_csv("unlabeled_data.csv")


### Description of Metadata 
*What data did you choose to address this research question? In what ways does this data shed light on the research question? What might its limitations be? [One paragraph description of the data, several plots or tables of relevant descriptive statistics about your data (e.g. how many documents? what are the length of the dos? tables of metadata? One paragraph discussion of value and limitations relevant to your question.]*

In [49]:
### Metadata

company_metadata_2024.head()

accession        time  \
0  0001002910-24-000056  2024-02-29   
1  0000004904-24-000020  2024-02-26   
2  0000874761-24-000011  2024-02-26   
3  0001634997-24-000031  2024-02-22   
4  0000066756-24-000007  2024-02-20   

                                                text ticker   naics  
0  PART I ITEM 1. BUSINESS GENERAL Ameren, formed...    AEE    2211  
1  PART I ITEM 1.   BUSINESS Overview and Descrip...    AEP    2211  
2  PART I In this Annual Report the terms “AES,” ...    AES   22111  
3  PART I Item 1. Business Overview Avangrid aspi...    AGR    2211  
4  Part I Item 1. Business Overview. ALLETE is a ...    ALE  221111

In [50]:
# Number of documents (rows) in the dataset
num_documents = company_metadata_2024.shape[0]
print(f"Number of documents: {num_documents}")


Number of documents: 149


In [51]:
# Number of unique companies (tickers)
num_unique_tickers = company_metadata_2024['ticker'].nunique()
print(f"Number of unique companies (tickers): {num_unique_tickers}")

# Number of unique NAICS codes
num_unique_naics = company_metadata_2024['naics'].nunique()
print(f"Number of unique NAICS codes: {num_unique_naics}")

# Frequency distribution of tickers
ticker_counts = company_metadata_2024['ticker'].value_counts()
print("\nFrequency of Each Ticker:")
print(ticker_counts)

# Frequency distribution of NAICS codes
naics_counts = company_metadata_2024['naics'].value_counts()
print("\nFrequency of Each NAICS Code:")
print(naics_counts)

Number of unique companies (tickers): 148
Number of unique NAICS codes: 26

Frequency of Each Ticker:
ticker
AR      2
AEE     1
OKE     1
NOVA    1
NRG     1
       ..
EPM     1
EQT     1
ES      1
ETR     1
WTI     1
Name: count, Length: 148, dtype: int64

Frequency of Each NAICS Code:
naics
2111      25
2211      21
22111     18
213112    17
211120    15
221210     8
221310     6
211130     5
212115     4
212220     4
212221     3
21211      3
213111     3
212114     2
211111     2
212230     2
212322     2
212325     1
212312     1
221114     1
21222      1
212313     1
212390     1
221        1
221111     1
212319     1
Name: count, dtype: int64


In [ ]:


## Dictionary approach





Climate list is: climate change, climate, global warming, clean air act, GHG, RPS, weather, rain, emission(s), carbon, carbon dioxide, carbon tax(es), cap-and-trade, sustainable, renewable, green.


Dictionary for 10k filoings to identify governmnt risk: 

Congress Government regulation(s) Political risk(s)
Congressional Government approval Politics
Debt ceiling Government debt(s) Price constraint(s)
Federal Government deficit(s) Price control(s)
Federal funds Government intervention(s) Price restriction(s)
Fiscal imbalance(s) Law(s) Regulation(s)
Government(s) Legal Regulatory
Government-approved Legislation Regulatory compliance
Government-sponsored Legislative Regulatory delay(s)
Governmental Legislatory Reimbursement(s)
Governmental program(s) Patent law(s) Subsidy
Government program(s) Political Subsidies
Governmental regulation(s) Political reform(s)




When I look at the most common words for my categories: 




To do: aftr calculating -- compare to the rating this 10-sentence chunk would have been given by the other measure. I tried to re-create the measure of Baz, using their dictionary approach. I foun the two dictionaries he was using 

Even before doing the analysis, my hunch was that my measure would be quite different, because the key words in my categories were: epa  3.834851
364       emiss  3.753358
475     fractur  3.695089
507   greenhous  3.695089
532     hydraul  3.617127
42          air  3.532570
172  climaterel  3.407407
788        pari  3.338414
489        gase  3.184263
697      methan  3.141703
495         ghg  3.097252
316      dioxid  3.097252
623        land  2.778798
117       biden  2.778798
680   mandatori  2.778798
843      presid  2.778798
171      climat  2.778798
472      fossil  2.736238
579     injunct  2.645267
100         ban  2.645267





In [53]:
import re
import nltk
from nltk.corpus import stopwords

# Download NLTK resources
nltk.download('stopwords')

# Define preprocessing function
def preprocess_text(text):
    # Remove numbers and punctuation except for hyphens
    text = re.sub(r'[^a-zA-Z\s-]', '', text)  # Keep only letters, spaces, and hyphens
    return text.lower()

# Function to create a CRE measure for a given SEC filing (document)
def calculate_cre(text, ccv_terms, gpv_terms):
    """
    Calculate the Climate Regulatory Exposure (CRE) measure for a firm's SEC filing.
    
    Args:
    - text: The preprocessed text of the SEC filing.
    - ccv_terms: A list of climate-related terms (CCV).
    - gpv_terms: A list of government policy-related terms (GPV).
    
    Returns:
    - cre: The computed Climate Regulatory Exposure (CRE) score (1 if both terms found, 0 otherwise).
    """
    # Preprocess the text
    processed_text = preprocess_text(text)
    
    # Initialize CRE score
    cre_score = 0
    
    # Check if any term in CCV dictionary is present in the text
    ccv_found = any(ccv_term in processed_text for ccv_term in ccv_terms)
    
    # Check if any term in GPV dictionary is present in the text
    gpv_found = any(gpv_term in processed_text for gpv_term in gpv_terms)
    
    # If both climate-related and government policy-related terms are found, assign a CRE score
    if ccv_found and gpv_found:
        cre_score = 1
    
    return cre_score

# Updated dictionaries

# Climate-related terms (CCV dictionary)
ccv_terms = [
    'climate change', 'climate', 'global warming', 'clean air act', 'ghg', 'rps', 
    'weather', 'rain', 'emission', 'carbon', 'carbon dioxide', 'carbon tax', 'cap-and-trade', 
    'sustainable', 'renewable', 'green'
]

# Government-related terms (GPV dictionary)
gpv_terms = [
    'congress', 'government regulation', 'political risk', 'congressional', 'government approval', 
    'politics', 'debt ceiling', 'government debt', 'price constraint', 'federal', 'government deficit', 
    'price control', 'federal funds', 'government intervention', 'price restriction', 'fiscal imbalance', 
    'law', 'regulation', 'government-approved', 'legislation', 'regulatory compliance', 'government-sponsored', 
    'legislative', 'regulatory delay', 'governmental', 'legislatory', 'reimbursement', 'government program', 
    'political', 'subsidy', 'government program', 'political', 'subsidies'
]

# Example document (SEC filing text)
example_text = """
    cap-and-trade government-sponsored
"""

# Calculate the CRE for the example document
cre = calculate_cre(example_text, ccv_terms, gpv_terms)
print(f"CRE score for the document: {cre}")


CRE score for the document: 1


[nltk_data] Downloading package stopwords to /Users/teri/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [54]:
# Apply the calculate_cre function to each row in the 'text' column and create a new 'CRE_score' column
labeled_270['CRE_score'] = labeled_270['chunk_text'].apply(lambda x: calculate_cre(x, ccv_terms, gpv_terms))

# Print the DataFrame with the new CRE_score column
print(labeled_270[['chunk_text', 'CRE_score']].tail(50))  # Display the first few rows with the CRE score

                                            chunk_text  CRE_score
220  Even if significant mineralization is discover...          0
221  Magnolia cannot ensure that the analogies draw...          1
222  The direct and indirect effects of negative pu...          1
223  We are also committed to helping employees upd...          1
224  Some of the properties in which we have an int...          0
225  We have cooperated with the DOJ and are not ab...          0
226  We may not be successful in consummating any a...          0
227  Because these efforts can be long-term in natu...          0
228  Risks Related to Ownership of NEP's Units NEP'...          0
229  Negative publicity regarding the managed healt...          0
230  These laws and regulations generally require I...          0
231  These estimates and assumptions are inherently...          0
232  Accordingly, repayment of our indebtedness wil...          0
233  Houston Electric and Indiana Electric are memb...          0
234  Hydra

In [55]:
# Create a new variable for jsut environemntal regulation
labeled_270['env_reg'] = labeled_270['regulation_type'].apply(lambda x: 1 if x in [1,3] else 0)

In [61]:
import numpy as np

np.corrcoef(labeled_270['env_reg'], labeled_270['CRE_score'])

array([[1.        , 0.50884745],
       [0.50884745, 1.        ]])

In [57]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#1 Accuracy 
accuracy = accuracy_score(labeled_270['env_reg'], labeled_270['CRE_score'])
print(f"Accuracy: {accuracy:.4f}")

# 2. Classification Report (precision, recall, F1-score)
class_report = classification_report(labeled_270['env_reg'], labeled_270['CRE_score'])
print("Testing Classification Report:")
print(class_report)

# 3. Confusion Matrix
conf_matrix = confusion_matrix(labeled_270['env_reg'], labeled_270['CRE_score'])
print("\nConfusion Matrix (Testing Data):")
print(conf_matrix)


Accuracy: 0.7963
Testing Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.82      0.86       200
           1       0.59      0.71      0.65        70

    accuracy                           0.80       270
   macro avg       0.74      0.77      0.75       270
weighted avg       0.81      0.80      0.80       270


Confusion Matrix (Testing Data):
[[165  35]
 [ 20  50]]


In [ ]:

#1 Accuracy 
accuracy = accuracy_score(labeled_270['regulation_present'], labeled_270['CRE_score'])
print(f"Accuracy: {accuracy:.4f}")

# 2. Classification Report (precision, recall, F1-score)
class_report = classification_report(labeled_270['regulation_present'], labeled_270['CRE_score'])
print("Testing Classification Report:")
print(class_report)

# 3. Confusion Matrix
conf_matrix = confusion_matrix(labeled_270['regulation_present'], labeled_270['CRE_score'])
print("\nConfusion Matrix (Testing Data):")
print(conf_matrix)

Accuracy: 0.8037
Testing Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.86      0.86       184
           1       0.69      0.69      0.69        86

    accuracy                           0.80       270
   macro avg       0.77      0.77      0.77       270
weighted avg       0.80      0.80      0.80       270


Confusion Matrix (Testing Data):
[[158  26]
 [ 27  59]]


In [ ]:
labeled_270.head(10)

ticker chunk_number                                         chunk_text  \
0    HES     chunk_14  However, various key stakeholders, including o...   
1    ENG     chunk_37  Our IT Director has over 20 years of experienc...   
2    ICD     chunk_14  As a result, the Primary Noteholders collectiv...   
3    PEG     chunk_41  Further, inaccurate results generated as a res...   
4    KRP     chunk_34  Our obligation to pay distributions on our Ser...   
5   PTEN     chunk_16  See “Item 1. Business – Risks and Insuranc...   
6   CDZI      chunk_1  ITEM 1A. Risk Factors Our business is subject ...   
7    NEE     chunk_12  NEE invests in gas and oil producing and trans...   
8    SUM      chunk_3  In addition, given the level of fixed and semi...   
9    OII     chunk_10  In order to manage some of the risks associate...   

   regulation_present  regulation_type  federal_regulation  state_regulation  \
0                   1              3.0                 0.0               1.0   
1                   0              0.0                 0.0               0.0   
2                   0              0.0                 0.0               0.0   
3                   1              3.0                 1.0               1.0   
4                   1              2.0                 0.0               0.0   
5                   0              0.0                 0.0               0.0   
6                   1              NaN                 NaN               NaN   
7                   0              0.0                 0.0               0.0   
8                   0              0.0                 0.0               0.0   
9                   0              0.0                 0.0               0.0   

   local_regulation                                              notes  \
0               1.0                                                NaN   
1               0.0                                                NaN   
2               0.0                                                NaN   
3               0.0                                                NaN   
4               0.0                              domestic and foreign    
5               0.0                                                NaN   
6               NaN  This regulation is more about property buildin...   
7               0.0                                                NaN   
8               0.0                                                NaN   
9               0.0                                                NaN   

   CRE_score  env_reg  
0          1        1  
1          0        0  
2          0        0  
3          1        1  
4          1        0  
5          0        0  
6          1        0  
7          1        0  
8          0        0  
9          0        0

In [63]:
# Summary statistics for numerical columns
summary_stats = unlabeled.describe()

# Display the summary statistics table
print(summary_stats)

       ticker chunk_number                                         chunk_text
count    5227         5227                                               5227
unique    135          105                                               5133
top        AR      chunk_2  Therefore, the classification and regulation o...
freq      186          133                                                  2


chaange the tru value to regulation beign just environemtnal not energy 